### ISSUE TITLE
[Feature 👩‍💻] 배포, 개발 환경 분리

### ISSUE THREAD

**Issue by yu-heejin** [Trip-In-World/Trip-In-World-Frontend#18]
## Description ✏️
* axios 세팅 및 배포, 개발 환경 분리

## TODO
- [x] axios.create 사용하기
- [x] 배포, 개발 환경 분리하기
- [x] module alias 설정하기
- [x] next.config env 설정하기
